<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Selecting & Retrieving Data with SQL

## 1.1 Let's first connect to our Database

In [1]:
# We will first load the sql extension into our environment
#
%load_ext sql

# Then connect to our in memory sqlite database
# NB: This database will cease to exist as soon as the database connection is closed
#
%sql sqlite://

'Connected: @None'

## 1.2 Importing Data From a CSV File

In [2]:
# Importing the python libraries that we will need in this notebook
#
import csv
import pandas as pd

Then we will download our csv file from Interpol: [here](https://bit.ly/InterpolDataset) and World Cup [here](http://bit.ly/MSWorldCupData)  . Open the link and then on our browser  Click File > Save Page As > Save. Lastly, upload it to our current environment on Colaboratory by clicking View > Table of Contents > Files then Upload.  (NB: Do not load file from url)

In [ ]:
# Loading the first table from a local CSV file
#
with open('Countries.csv','r') as f:
    Interpol = pd.read_csv(f, index_col=0, encoding='utf-8') 

# Then storing it in an SQL table of our in memory sqlite database
#
#%sql DROP TABLE if EXISTS Interpol;
%sql PERSIST Interpol;

In [4]:
# We will load all the other dataset that we will need i.e. WorldCup
#
with open('WorldCup.csv','r') as f:
    WorldCup = pd.read_csv(f, index_col=0, encoding='utf-8') 
    
#%sql DROP TABLE if EXISTS WorldCup;
%sql PERSIST WorldCup;

 * sqlite://

'Persisted worldcup'

In [ ]:
# Let's preview our Interpol table so that we can understand it
# Try to understand all the attributes (i.e columns) since this
# will be one of the datasets that we will work with through this session
#
%%sql
 select * from Interpol limit 5;

In [ ]:
# Let's preview our Worldcup table so that we can also understand it.
# You will be acting as a football commentator performing research on the 
# world cup matches played in the past.
# 
%sql SELECT * FROM WorldCup limit 5;

## 1.3 Select Single Columns

In [ ]:
# Example 1
# This is how we will select a single column (i.e. the Country Column) from the Interpol Dataset
#
%%sql
SELECT Country FROM Interpol;

In [ ]:
# Example 2
# Let's get the European countries without National fugitives  
# 
%%sql
SELECT Country FROM Interpol
WHERE "National Fugitives" = 0 AND Region = "Europe"

In [ ]:
# Example 3
# Let's select the regions without National fugitives
#
%%sql
SELECT * FROM Interpol

### <font color="green"> 1.3 Challenges</font>

In [ ]:
# Challenge 1
# Using the Interpol Dataset, let us get the Northern African countries that  
# do not host possible fugitives or captured fugitives
# 
%%sql
SELECT country from Interpol
WHERE "Possible Hosted Fugitives/Captured Fugitives" = 0 AND Region = "Northern Africa";

 * sqlite://
Done.

[]

In [ ]:
# Challenge 2
# Using the Interpol Dataset, let us get the countries without a National fugitive and a Wanted fugitive
#
%%sql
SELECT country from Interpol
WHERE "National Fugitive" = 0  and "Wanted Fugitive" = 0;

 * sqlite://
Done.

[]

In [ ]:
# Challenge 3
# Using the Interpol Dataset, which european countries have 3 National Fugitives
# 
%%sql
SELECT * from Interpol
WHERE 'National Fugitive' = 3 AND Region = 'Europe';

 * sqlite://
Done.

[]

## 1.4 Multiple columns

In [ ]:
# Example 1
# Using the Interpol dataset, we would like to know the countries and their respective No. of Captured fugitives.
#
%%sql
SELECT Country, "Possible Hosted Fugitives / Captured Fugitives" FROM Interpol;

In [ ]:
# Example 2
# Using the world cup dataset, let's get teams that played in the matches with their respective referee
# 
%%sql
SELECT "Home_Team_Name", "Away_Team_Name", Referee FROM WorldCup;

In [ ]:
# Example 3
# Find out any three matches that have had 5 away goals  
#
%%sql
SELECT * FROM WorldCup Where "Away_Team_Goals" = 5 LIMIT 3

### <font color="green"> 1.4 Challenges</font>

In [ ]:
# Challenge 1
# From the Interpol dataset, let's get countries with their respective 
# No. of National fugitives and Wanted fugitives
# 
%%sql
SELECT country, "National Fugitives", "Wanted Fugitives" from Interpol

In [14]:
# Challenge 2
# Using WorldCup dataset, find out which group 4 world cup matches 
# that were played in the city of Montevideo 
#

%%sql
SELECT * from WorldCup
WHERE City ="Montevideo" and Stage = "Group 4";

 * sqlite://
Done.

[]

In [ ]:
# Challenge 3
# Answering the same question as challenge 2, we would like to get only one match
# 
# OUR CODE GOES HERE
WorldCup.head(2)

                  Datetime    Stage  ... Home_Team_Initials Away_Team_Initials
Year                                 ...
1930  13 Jul 1930 - 15:00   Group 1  ...                FRA                MEX
1930  13 Jul 1930 - 15:00   Group 4  ...                USA                BEL

[2 rows x 19 columns]

In [ ]:
WorldCup["City"].value_counts()

Mexico City        23
Rio De Janeiro     18
Montevideo         18
Guadalajara        17
Johannesburg       15
                   ..
Antibes             1
Reims               1
Udevalla            1
Trieste             1
Lille               1
Name: City, Length: 151, dtype: int64

In [ ]:
%%sql
SELECT * FROM WorldCup 
WHERE City="Montevideo " AND Stage="Group 1";

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '15 Jul 1930 - 16:00 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Argentina', 1, 0, 'France', ' ', 23409.0, 0, 0, 'REGO Gilberto (BRA)', 'SAUCEDO Ulises (BOL)', 'RADULESCU Constantin (ROU)', 201, 1085, 'ARG', 'FRA'),
 (1930, '16 Jul 1930 - 14:45 ', 'Group 1', 'Parque Central', 'Montevideo ', 'Chile', 3, 0, 'Mexico', ' ', 9249.0, 1, 0, 'CRISTOPHE Henry (BEL)', 'APHESTEGUY Martin (URU)', 'LANGENUS Jean (BEL)', 201, 1095, 'CHI', 'MEX'),
 (1930, '19 Jul 1930 - 12:50 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Chile', 1, 0, 'France', ' ', 2000.0, 0, 0, 'TEJADA Anibal (URU)', 'LOMBARDI Domingo (URU)', 'REGO Gilberto (BRA)', 201, 1094, 'CHI', 'FRA'),
 (1930, '19 Jul 1930 - 15:00 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Argentina', 6, 3, 'Mexico', ' ', 42100.0, 3, 1, 'SAUCEDO Ulises (BOL)', 'ALONSO Gualberto (URU)', 'RADULESCU Constantin (ROU)', 201, 1086, 'ARG', 'MEX'),
 (1930, '22 Jul 1930 - 14:45 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Argentina', 3, 1, 'Chile', ' ', 41459.0, 2, 1, 'LANGENUS Jean (BEL)', 'CRISTOPHE Henry (BEL)', 'SAUCEDO Ulises (BOL)', 201, 1084, 'ARG', 'CHI')]

In [ ]:
%%sql
SELECT * FROM Interpol LIMIT 10;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif')]

In [ ]:
# SELECT Country FROM Interpol LIMIT 10;
Interpol.columns.values

array(['National Fugitives', 'Wanted Fugitives',
       'Possible Hosted Fugitives / Captured Fugitives', 'Region', 'Flag'],
      dtype=object)

## 1.5 Orderby

In [ ]:
# Example 1
# Using the Interpol dataset, let's get all our records ordering 
# them by the region in ascending order
#
%%sql
SELECT * FROM Interpol
ORDER BY Region ASC;

In [ ]:
# Example 2
# We can do the same as in example 1 but now having the records in descending order 
# as shown below
#
%%sql
SELECT * FROM Interpol
ORDER BY Country DESC;

In [ ]:
# Example 3 
# Using the Worldcup dataset, we can select 5 World Cup Group 1 matches played 
# after 1950 and having them ordered by city in ascending order as shown below
#
%%sql
SELECT * FROM WorldCup
WHERE Stage='Group 1' AND Year = 1950
ORDER BY City ASC
LIMIT 5;

### <font color="green"> 1.5 Challenges</font>

In [ ]:
# Challenge 1
# Using Interpol Dataset, select all the records and order them by National Fugitives in ascending order
# 
%%sql
SELECT * from Interpol
ORDER BY 'Nation Fugitive' ASC;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Botswana', 0, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Brazil', 2, 4, 3, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Cayman Islands', 0, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Chile', 1, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Congo', 0, 0, 1, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Costa Rica', 0, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Curaçao', 0, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Dominican Republic', 1, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('Ecuador', 0, 0, 1, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Honduras', 1, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Kenya', 1, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Lesotho', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Mali', 0, 1, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Morocco', 2, 0, 3, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Mozambique', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Namibia', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('New Zealand', 0, 0, 1, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Nicaragua', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Panama', 0, 0, 2, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Paraguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Peru', 2, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Russia', 2, 1, 3, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Somalia', 1, 0, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Swaziland', 1, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif')]

In [ ]:
# Challenge 2
# Using WorldCup Dataset, get the matches played in the Pocitos stadium and their attendance 
# later than 1950 and ordering them by attendance in descending order
# 
%%sql
SELECT MatchID, Attendance from WorldCup
WHERE stadium = "Pocitos" and year < 1950
ORDER BY 'Attendance' ASC;

 * sqlite://
Done.

[(1096, 4444.0), (1098, 2549.0)]

In [ ]:
# Challenge 3
# Get the World Cup Matches played in France after 1970 ordered by years in descending order 
#
%%sql
SELECT MatchID, stage, year from WorldCup
WHERE Home_Team_Name = 'France' and Year > 1970
ORDER BY YEAR DESC;

 * sqlite://
Done.

[(300186485, 'Quarter-finals', 2014),
 (300186462, 'Round of 16', 2014),
 (300186485, 'Quarter-finals', 2014),
 (300186462, 'Round of 16', 2014),
 (300186496, 'Group E', 2014),
 (300061449, 'Group A', 2010),
 (300061451, 'Group A', 2010),
 (97410029, 'Group G', 2006),
 (97410013, 'Group G', 2006),
 (43950018, 'Group A', 2002),
 (43950001, 'Group A', 2002),
 (8786, 'Semi-finals', 1998),
 (8776, 'Round of 16', 1998),
 (8762, 'Group C', 1998),
 (8745, 'Group C', 1998),
 (8730, 'Group C', 1998),
 (422, 'Match for third place', 1986),
 (564, 'Semi-finals', 1986),
 (571, 'Group C', 1986),
 (920, 'Group 4', 1982),
 (922, 'Group 4', 1982),
 (919, 'Group 4', 1982),
 (2344, 'Group 1', 1978)]

## 1.6 Where

In [ ]:
# Example 1
# From our Interpol dataset, let's find out which Countries have had three or more than three National Fugitives.
#
%%sql
SELECT * FROM Interpol
WHERE "National Fugitives" = 3;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif')]

In [ ]:
# Example 2
# From our Interpol dataset, let's get the European countries and the no of Wanted fugitives they have
#
%%sql
SELECT Country, "Wanted Fugitives" FROM Interpol
WHERE Region = 'Europe';

 * sqlite://
Done.

[('Albania', 3),
 ('Austria', 1),
 ('Belarus', 1),
 ('Belgium', 2),
 ('Croatia', 1),
 ('Czech Republic', 3),
 ('Denmark', 2),
 ('Estonia', 2),
 ('Finland', 2),
 ('France', 0),
 ('Germany', 0),
 ('Greece', 1),
 ('Hungary', 2),
 ('Ireland', 1),
 ('Italy', 1),
 ('Lithuania', 1),
 ('Macedonia', 0),
 ('Malta', 0),
 ('Montenegro', 2),
 ('Norway', 1),
 ('Poland', 4),
 ('Romania', 4),
 ('Serbia', 0),
 ('Slovakia', 2),
 ('Spain', 2),
 ('Sweden', 3),
 ('The Netherlands', 3),
 ('Turkey', 0),
 ('Ukraine', 1),
 ('United Kingdom', 4)]

In [ ]:
# Example 3
# From our WorldCup dataset, Let us select the home teams, away teams 
# and the respective no. of home team goals, no. of away team goals
# for the years after 1950
#
%%sql
SELECT Year, Stage, Home_Team_Name, Home_Team_Goals, Away_Team_Name, Away_Team_Goals FROM WorldCup
WHERE Year > 1930
LIMIT 7;

 * sqlite://
Done.

[(1934, 'Preliminary round', 'Austria', 3, 'France', 2),
 (1934, 'Preliminary round', 'Hungary', 4, 'Egypt', 2),
 (1934, 'Preliminary round', 'Switzerland', 3, 'Netherlands', 2),
 (1934, 'Preliminary round', 'Sweden', 3, 'Argentina', 2),
 (1934, 'Preliminary round', 'Germany', 5, 'Belgium', 2),
 (1934, 'Preliminary round', 'Spain', 3, 'Brazil', 1),
 (1934, 'Preliminary round', 'Italy', 7, 'USA', 1)]

### <font color="green"> 1.6 Challenges</font>

In [ ]:
# Challenge 1
# From our Interpol dataset, find out which  country had the most Captured Fugitives 
#
%%sql
SELECT country, "Possible Hosted Fugitives / Captured Fugitives" from Interpol
ORDER BY "Possible Hosted Fugitives / Captured Fugitives" DESC
LIMIT 1;

 * sqlite://
Done.

[('Spain', 13)]

In [ ]:
# Challenge 2
# Using our Interpol dataset, get the european and asian countries;
#
%%sql
SELECT * from Interpol
WHERE Region = 'Asia' or Region = 'Europe';

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif')]

In [ ]:
# Challenge 3 
# From our Interpol dataset, find out which top countries had the least National fugities
#
%%sql
SELECT country, "National Fugitives" from Interpol
ORDER BY "National Fugitives" ASC
LIMIT 10;

 * sqlite://
Done.

[('Angola', 0),
 ('Belgium', 0),
 ('Bolivia', 0),
 ('Botswana', 0),
 ('Cambodia', 0),
 ('Cayman Islands', 0),
 ('Congo', 0),
 ('Costa Rica', 0),
 ('Curaçao', 0),
 ('Denmark', 0)]

## 1.7 Between

In [ ]:
# Example 1
# Select the countries with national fugitives between 0 and 3 ordered by nationnal fugitives ascending order
#
%%sql
SELECT Country, "National Fugitives" FROM Interpol
WHERE "National Fugitives" BETWEEN 0 AND 3 ORDER BY "National Fugitives" ASC;

 * sqlite://
Done.

[('Angola', 0),
 ('Belgium', 0),
 ('Bolivia', 0),
 ('Botswana', 0),
 ('Cambodia', 0),
 ('Cayman Islands', 0),
 ('Congo', 0),
 ('Costa Rica', 0),
 ('Curaçao', 0),
 ('Denmark', 0),
 ('Ecuador', 0),
 ('France', 0),
 ('India', 0),
 ('Lesotho', 0),
 ('Macedonia', 0),
 ('Mali', 0),
 ('Malta', 0),
 ('Mozambique', 0),
 ('Namibia', 0),
 ('New Zealand', 0),
 ('Norway', 0),
 ('Panama', 0),
 ('Qatar', 0),
 ('Serbia', 0),
 ('Tanzania', 0),
 ('Turkey', 0),
 ('Venezuela', 0),
 ('Zimbabwe', 0),
 ('Australia', 1),
 ('Austria', 1),
 ('Belarus', 1),
 ('Belize', 1),
 ('Chile', 1),
 ('Croatia', 1),
 ('Dominican Republic', 1),
 ('Estonia', 1),
 ('Germany', 1),
 ('Greece', 1),
 ('Honduras', 1),
 ('Indonesia', 1),
 ('Iraq', 1),
 ('Italy', 1),
 ('Kenya', 1),
 ('Lithuania', 1),
 ('Nicaragua', 1),
 ('Pakistan', 1),
 ('Paraguay', 1),
 ('Somalia', 1),
 ('Spain', 1),
 ('Swaziland', 1),
 ('Ukraine', 1),
 ('Uruguay', 1),
 ('Zambia', 1),
 ('Argentina', 2),
 ('Bangladesh', 2),
 ('Brazil', 2),
 ('El Salvador', 2),
 ('Finland', 2),
 ('Georgia, Asia', 2),
 ('Hungary', 2),
 ('Ireland', 2),
 ('Morocco', 2),
 ('Peru', 2),
 ('Russia', 2),
 ('Slovakia', 2),
 ('Sweden', 2),
 ('Albania', 3),
 ('Canada', 3),
 ('Colombia', 3),
 ('Czech Republic', 3),
 ('Mexico', 3),
 ('Montenegro', 3),
 ('South Africa', 3)]

In [ ]:
# Example 2
# Select the countries with national fugitives not between 0 and 4 ordered by nationnal fugitives ascending order
#
%%sql
SELECT Country, "National Fugitives" FROM Interpol
WHERE "National Fugitives" NOT BETWEEN 0 AND 4 ORDER BY "National Fugitives" ASC;

 * sqlite://
Done.

[('The Netherlands', 6), ('United Kingdom', 6), ('United States', 8)]

In [ ]:
# Example 3
# Select any 5 matches played after 1950 which did not have the home team as Germany
#
%%sql
SELECT * FROM WorldCup
WHERE NOT "Home Team Name" = 'Germany' AND NOT Year < 1950
LIMIT 5;

 * sqlite://
Done.

[(1950, '24 Jun 1950 - 15:00 ', 'Group 1', 'Maracan� - Est�dio Jornalista M�rio Filho', 'Rio De Janeiro ', 'Brazil', 4, 0, 'Mexico', ' ', 81649.0, 1, 0, 'READER George (ENG)', 'GRIFFITHS Benjamin (WAL)', 'MITCHELL George (SCO)', 208, 1187, 'BRA', 'MEX'),
 (1950, '25 Jun 1950 - 15:00 ', 'Group 2', 'Maracan� - Est�dio Jornalista M�rio Filho', 'Rio De Janeiro ', 'England', 2, 0, 'Chile', ' ', 29703.0, 1, 0, 'VAN DER MEER Karel (NED)', 'GARDELLI Mario (BRA)', 'DAHLNER Gunnar (SWE)', 208, 1192, 'ENG', 'CHI'),
 (1950, '25 Jun 1950 - 15:00 ', 'Group 2', 'Durival de Brito', 'Curitiba ', 'Spain', 3, 1, 'USA', ' ', 9511.0, 0, 1, 'VIANA Mario (BRA)', 'DA COSTA VIEIRA Jose (POR)', 'DE LA SALLE Charles (FRA)', 208, 1208, 'ESP', 'USA'),
 (1950, '25 Jun 1950 - 15:00 ', 'Group 3', 'Pacaembu', 'Sao Paulo ', 'Sweden', 3, 2, 'Italy', ' ', 36502.0, 2, 1, 'LUTZ Jean (SUI)', 'BERANEK Alois (AUT)', 'TEJADA Carlos (MEX)', 208, 1219, 'SWE', 'ITA'),
 (1950, '25 Jun 1950 - 15:00 ', 'Group 1', 'Independencia', 'Belo Horizonte ', 'Yugoslavia', 3, 0, 'Switzerland', ' ', 7336.0, 0, 0, 'GALEATI Giovanni (ITA)', 'EKLIND Ivan (SWE)', 'DATTILO Generoso (ITA)', 208, 1230, 'YUG', 'SUI')]

### <font color="green"> 1.7 Challenges</font>

In [ ]:
# Challenge 1
# From the Interpol dataset, get all asian countries with wanted fugitives between 0 and 2
#
%%sql 
SELECT * from Interpol
WHERE Region = "Asia" and "Wanted Fugitives" BETWEEN 0 AND 2;

 * sqlite://
Done.

[('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg')]

In [ ]:
# Challenge 2
# From the World cup dataset, get all the matches that were played later than 1980 with an attendance less than 5000 
# 
%%sql
SELECT * from WorldCup
WHERE NOT "Attendance" > 5000 and NOT Year < 1890;

 * sqlite://
Done.

[(1930, '13 Jul 1930 - 15:00 ', 'Group 1', 'Pocitos', 'Montevideo ', 'France', 4, 1, 'Mexico', ' ', 4444.0, 3, 0, 'LOMBARDI Domingo (URU)', 'CRISTOPHE Henry (BEL)', 'REGO Gilberto (BRA)', 201, 1096, 'FRA', 'MEX'),
 (1930, '14 Jul 1930 - 14:50 ', 'Group 3', 'Pocitos', 'Montevideo ', 'Romania', 3, 1, 'Peru', ' ', 2549.0, 1, 0, 'WARNKEN Alberto (CHI)', 'LANGENUS Jean (BEL)', 'MATEUCCI Francisco (URU)', 201, 1098, 'ROU', 'PER'),
 (1930, '19 Jul 1930 - 12:50 ', 'Group 1', 'Estadio Centenario', 'Montevideo ', 'Chile', 1, 0, 'France', ' ', 2000.0, 0, 0, 'TEJADA Anibal (URU)', 'LOMBARDI Domingo (URU)', 'REGO Gilberto (BRA)', 201, 1094, 'CHI', 'FRA'),
 (1934, '31 May 1934 - 16:30 ', 'Quarter-finals', 'San Siro', 'Milan ', 'Germany', 2, 1, 'Sweden', ' ', 3000.0, 0, 0, 'BARLASSINA Rinaldo (ITA)', 'MERCET Rene (SUI)', 'VAN MOORSEL Johannes (NED)', 418, 1129, 'GER', 'SWE'),
 (1950, '02 Jul 1950 - 15:40 ', 'Group 1', 'Eucaliptos', 'Porto Alegre ', 'Switzerland', 2, 1, 'Mexico', ' ', 3580.0, 2, 0, 'EKLIND Ivan (SWE)', 'DAHLNER Gunnar (SWE)', 'BUSTAMANTE Sergio (CHI)', 208, 1222, 'SUI', 'MEX'),
 (1954, '20 Jun 1954 - 17:00 ', 'Group 2', 'Charmilles', 'Geneva ', 'Turkey', 7, 0, 'Korea Republic', ' ', 4000.0, 4, 0, 'MARINO Esteban (URU)', 'ORLANDINI Vincenzo (ITA)', 'SCHONHOLZER Ernest (SUI)', 211, 1304, 'TUR', 'KOR'),
 (1958, '17 Jun 1958 - 19:00 ', 'Group 3', 'Rasunda Stadium', 'Solna ', 'Wales', 2, 1, 'Hungary', ' ', 2823.0, 0, 1, 'LATYCHEV Nikolaj (URS)', 'CODESAL Jose Maria (URU)', 'ERIKSSON Arne (FIN)', 220, 1408, 'WAL', 'HUN')]

In [ ]:
# Challenge 3 
# Which matches were played between the year 1990 and 2000?
# 
%%sql
SELECT * from WorldCup
WHERE Year BETWEEN 1990 AND 2000
LIMIT 10;

 * sqlite://
Done.

[(1990, '08 Jun 1990 - 18:00 ', 'Group B', 'Giuseppe Meazza', 'Milan ', 'Argentina', 0, 1, 'Cameroon', ' ', 73780.0, 0, 0, 'VAUTROT Michel (FRA)', 'MAURO Vincent (USA)', 'LISTKIEWICZ Michal (POL)', 322, 26, 'ARG', 'CMR'),
 (1990, '09 Jun 1990 - 17:00 ', 'Group B', 'Stadio San Nicola', 'Bari ', 'Soviet Union', 0, 2, 'Romania', ' ', 42907.0, 0, 1, 'CARDELLINO DE SAN VICENTE Juan (URU)', 'SORIANO ALADREN Emilio (ESP)', 'SILVA ARCE Hernan (CHI)', 322, 342, 'URS', 'ROU'),
 (1990, '09 Jun 1990 - 17:00 ', 'Group D', 'Renato Dall Ara', 'Bologna ', 'rn">United Arab Emirates', 0, 2, 'Colombia', ' ', 30791.0, 0, 0, 'COURTNEY George (ENG)', 'TAKADA Shizuo (JPN)', 'SNODDY Alan (NIR)', 322, 119, 'UAE', 'COL'),
 (1990, '09 Jun 1990 - 21:00 ', 'Group A', 'Stadio Olimpico', 'Rome ', 'Italy', 1, 0, 'Austria', ' ', 73303.0, 0, 0, 'RAMIZ WRIGHT Jose (BRA)', 'PEREZ HOYOS Armando (COL)', 'SILVA VALENTE Carlos Alberto (POR)', 322, 42, 'ITA', 'AUT'),
 (1990, '10 Jun 1990 - 17:00 ', 'Group A', 'Comunale', 'Florence ', 'USA', 1, 5, 'Czechoslovakia', ' ', 33266.0, 0, 2, 'ROETHLISBERGER Kurt (SUI)', 'VAN LANGENHOVE Marcel (BEL)', 'SCHMIDHUBER Aron (GER)', 322, 355, 'USA', 'TCH'),
 (1990, '10 Jun 1990 - 21:00 ', 'Group C', 'Stadio delle Alpi', 'Turin ', 'Brazil', 2, 1, 'Sweden', ' ', 62628.0, 1, 0, 'LANESE Tullio (ITA)', 'VAUTROT Michel (FRA)', 'JOUINI Neji (TUN)', 322, 75, 'BRA', 'SWE'),
 (1990, '10 Jun 1990 - 21:00 ', 'Group D', 'Giuseppe Meazza', 'Milan ', 'Germany FR', 4, 1, 'Yugoslavia', ' ', 74765.0, 2, 0, 'MIKKELSEN Peter (DEN)', 'MANDI Jassim (BHR)', 'LISTKIEWICZ Michal (POL)', 322, 201, 'FRG', 'YUG'),
 (1990, '11 Jun 1990 - 17:00 ', 'Group C', 'Luigi Ferraris', 'Genoa ', 'Costa Rica', 1, 0, 'Scotland', ' ', 30867.0, 0, 0, 'LOUSTAU Juan (ARG)', 'MACIEL Carlos (PAR)', 'JACOME GUERRERO Elias V. (ECU)', 322, 127, 'CRC', 'SCO'),
 (1990, '11 Jun 1990 - 21:00 ', 'Group F', 'Sant Elia', 'Cagliari ', 'England', 1, 1, 'rn">Republic of Ireland', ' ', 35238.0, 1, 0, 'SCHMIDHUBER Aron (GER)', 'FREDRIKSSON Erik (SWE)', 'ROETHLISBERGER Kurt (SUI)', 322, 161, 'ENG', 'IRL'),
 (1990, '12 Jun 1990 - 17:00 ', 'Group E', 'Marc Antonio Bentegodi', 'Verona ', 'Belgium', 2, 0, 'Korea Republic', ' ', 32790.0, 0, 0, 'MAURO Vincent (USA)', 'SNODDY Alan (NIR)', 'COURTNEY George (ENG)', 322, 57, 'BEL', 'KOR')]

## 1.8 Distinct

In [ ]:
# Example 1
# Let's find out which stadiums have hosted world cup matches
%%sql
SELECT DISTINCT Stadium FROM WorldCup;

In [ ]:
# Example 2
# Let's find out which world cup cities have hosted world cup matches after 2000
#
%%sql
SELECT DISTINCT City FROM WorldCup WHERE Year > 2000;

### <font color="green"> 1.8 Challenges</font>

In [ ]:
# Challenge 1
# Name the stages in the world cup and order them alphabetically by stage.
# 
%%sql
SELECT DISTINCT stage from WorldCup
ORDER BY stage;

In [ ]:
# Challenge 2
# Which cities hosted the world cup between 1950 and 2000?
#
%%sql
SELECT DISTINCT city from WorldCup
WHERE Year BETWEEN 1950 AND 2000;

 * sqlite://
Done.

[('Rio De Janeiro ',),
 ('Curitiba ',),
 ('Sao Paulo ',),
 ('Belo Horizonte ',),
 ('Porto Alegre ',),
 ('Recife ',),
 ('Berne ',),
 ('Zurich ',),
 ('Geneva ',),
 ('Lausanne ',),
 ('Basel ',),
 ('Lugano ',),
 ('Solna ',),
 ('Gothenburg ',),
 ('Malm� ',),
 ('Sandviken ',),
 ('Norrk�Ping ',),
 ('Vasteras ',),
 ('Udevalla ',),
 ('Halmstad ',),
 ('Boras ',),
 ('Helsingborg ',),
 ('Eskilstuna ',),
 ('Orebro ',),
 ('Arica ',),
 ('Vina Del Mar ',),
 ('Rancagua ',),
 ('Santiago De Chile ',),
 ('London ',),
 ('Sheffield ',),
 ('Liverpool ',),
 ('Middlesbrough ',),
 ('Manchester ',),
 ('Birmingham ',),
 ('Sunderland ',),
 ('Mexico City ',),
 ('Puebla ',),
 ('Leon ',),
 ('Guadalajara ',),
 ('Toluca ',),
 ('Frankfurt/Main ',),
 ('Berlin West ',),
 ('Hamburg ',),
 ('Dortmund ',),
 ('Hanover ',),
 ('D�Sseldorf ',),
 ('Munich ',),
 ('Stuttgart ',),
 ('Gelsenkirchen ',),
 ('Buenos Aires ',),
 ('Mar Del Plata ',),
 ('Rosario ',),
 ('Cordoba ',),
 ('Mendoza ',),
 ('Barcelona ',),
 ('Vigo ',),
 ('Seville ',),
 ('La Coru�A ',),
 ('Elche ',),
 ('Malaga ',),
 ('Gijon ',),
 ('Bilbao ',),
 ('Valencia ',),
 ('Oviedo ',),
 ('Valladolid ',),
 ('Zaragoza ',),
 ('Alicante ',),
 ('Madrid ',),
 ('Irapuato ',),
 ('Monterrey ',),
 ('Nezahualcoyotl ',),
 ('Queretaro ',),
 ('Milan ',),
 ('Bari ',),
 ('Bologna ',),
 ('Rome ',),
 ('Florence ',),
 ('Turin ',),
 ('Genoa ',),
 ('Cagliari ',),
 ('Verona ',),
 ('Palermo ',),
 ('Udine ',),
 ('Naples ',),
 ('Dallas ',),
 ('Chicago ',),
 ('Detroit ',),
 ('New York/New Jersey ',),
 ('Los Angeles ',),
 ('Orlando ',),
 ('Washington Dc ',),
 ('San Francisco ',),
 ('Boston ',),
 ('Saint-Denis ',),
 ('Montpellier ',),
 ('Bordeaux ',),
 ('Toulouse ',),
 ('Lens ',),
 ('Marseilles ',),
 ('Nantes ',),
 ('Lyon ',),
 ('Saint-Etienne ',),
 ('Paris ',)]

In [ ]:
# Challenge 3
# During which years was the world cup hosted in?
#
%%sql
SELECT DISTINCT Year from WorldCup;

 * sqlite://
Done.

[(1930,),
 (1934,),
 (1938,),
 (1950,),
 (1954,),
 (1958,),
 (1962,),
 (1966,),
 (1970,),
 (1974,),
 (1978,),
 (1982,),
 (1986,),
 (1990,),
 (1994,),
 (1998,),
 (2002,),
 (2006,),
 (2010,),
 (2014,)]

## 1.9 Count

In [ ]:
# Example 1
# How many countries were listed in interpol's data? 
#
%%sql
SELECT COUNT(Country) FROM Interpol;

In [ ]:
# Example 2
# How many times has Brazil played home during world cup matches?
#
%%sql
SELECT COUNT("Home_Team_Name") FROM WorldCup where Home_Team_Name = 'Brazil';

In [ ]:
# Example 3
# Find out the number of times that stadiums have hosted matches in the World Cup? 
# 
%%sql
SELECT COUNT(Stadium)
FROM WorldCup;

### <font color="green"> 1.9 Challenges</font>

In [ ]:
# Challenge 1
# Using Interpol Dataset, find out how many wanted fugitives there are in Northern Africa.
# 
%%sql
SELECT COUNT ("Wanted Fugitives") from Interpol
WHERE Region = "Northern Africa";

 * sqlite://
Done.

[(2,)]

In [ ]:
# Challenge 2
# Using WorldCup Dataset, find out how many Possible Hosted Fugitives / Captured Fugitives 
# there are in Europe and Northern Africa.
# 
%%sql
SELECT COUNT("Possible Hosted Fugitives / Captured Fugitives") from Interpol
WHERE Region = "Europe" or "Northern Africa";

 * sqlite://
Done.

[(30,)]

In [ ]:
# Challenge 3
# Using WorldCup dataset, find out how many away teams were played where a team scored more than 3 goals.
# 
%%sql
SELECT COUNT("Away_Team_Name") from WorldCup
WHERE Home_Team_Goals >3 or Away_Team_Goals >3;

 * sqlite://
Done.

[(128,)]

## 1.10 Groupby

In [ ]:
# Example 1
# Which three stadiums have hosted the most world cup games?
#
%%sql
SELECT Stadium, COUNT(Stadium)
FROM WorldCup
GROUP BY Stadium 
ORDER BY COUNT(Stadium) DESC LIMIT 3;

In [ ]:
# Example 2
# Which three stadiums have hosted the least world cup games?
#
%%sql
SELECT City, COUNT(Stadium)
FROM WorldCup
GROUP BY stadium 
ORDER BY COUNT(Stadium) ASC LIMIT 3;

### <font color="green"> 1.10 Challenges</font>

In [ ]:
# Challenge 1
# What has been the largest no. of home goals scored by three home teams? 
# 
%%sql
SELECT "Home_Team_Name", COUNT("Home_Team_Goals") from WorldCup
GROUP BY "Home_Team_Name"
ORDER BY COUNT("Home_Team_Goals") DESC
LIMIT 3;

In [ ]:
# Challenge 2
# Which away teams have scored the lowest no. of away goals?
# 
%%sql
SELECT "Away_Team_Name", COUNT("Away_Team_Goals") from WorldCup
GROUP BY "Away_Team_Name"
ORDER BY COUNT("Away_Team_Goals") ASC
LIMIT 3;

In [ ]:
# Challenge 3
# Select records from the World Cup Dataset grouping by City 
# 
%%sql
SELECT * from WorldCup
GROUP BY city;

##1.11 Null Values

In [ ]:
# Example 1
# Select any one record from the world cup dataset that has null examples?
# 
%%sql
SELECT *
FROM WorldCup
WHERE Attendance IS NULL LIMIT 1;

In [ ]:
# Example 2
# Select any 5 records without null examples from the Worldcup Dataset 
#
%%sql
SELECT *
FROM WorldCup
WHERE City IS NOT NULL
LIMIT 5;

### <font color="green"> 1.11 Challenges</font>

In [ ]:
# Challenge 1
# Using the Worldcup dataset, select all the records that contain null values?
#
%%sql
SELECT * from WorldCup
WHERE "Home_Team_Goals" is NULL;

 * sqlite://
Done.

[]

In [ ]:
# Challenge 2
# Select all the records that do not contain null values from the Interpol dataset
#
%%sql
SELECT * from Interpol
WHERE "Wanted Fugitives" is not NULL;

 * sqlite://
Done.

[('Albania', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/al.gif'),
 ('Angola', 0, 0, 1, 'Northern Africa', 'http://www.crwflags.com/fotw/images/a/ao.gif'),
 ('Argentina', 2, 2, 1, 'South America', 'http://www.crwflags.com/fotw/images/a/ar.gif'),
 ('Australia', 1, 1, 2, 'Oceania', 'http://www.crwflags.com/fotw/images/a/au.gif'),
 ('Austria', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/a/at.gif'),
 ('Bangladesh', 2, 1, 1, 'Asia', 'http://www.crwflags.com/fotw/images/b/bd.gif'),
 ('Belarus', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/by.gif'),
 ('Belgium', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/b/be.gif'),
 ('Belize', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/b/bz.gif'),
 ('Bolivia', 0, 0, 2, 'South America', 'http://www.crwflags.com/fotw/images/b/bo.gif'),
 ('Botswana', 0, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/b/bw.gif'),
 ('Brazil', 2, 4, 3, 'South America', 'http://www.crwflags.com/fotw/images/b/br.gif'),
 ('Cambodia', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/k/kh.gif'),
 ('Canada', 3, 4, 2, 'North America', 'http://www.crwflags.com/fotw/images/c/ca.gif'),
 ('Cayman Islands', 0, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/k/ky.gif'),
 ('Chile', 1, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/c/cl.gif'),
 ('Colombia', 3, 0, 1, 'South America', 'http://www.crwflags.com/fotw/images/c/co.gif'),
 ('Congo', 0, 0, 1, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/c/cg.gif'),
 ('Costa Rica', 0, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/c/cr.gif'),
 ('Croatia', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/h/hr.gif'),
 ('Curaçao', 0, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/c/cw.gif'),
 ('Czech Republic', 3, 3, 0, 'Europe', 'http://www.crwflags.com/fotw/images/c/cz.gif'),
 ('Denmark', 0, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/d/dk.gif'),
 ('Dominican Republic', 1, 1, 2, 'Central America', 'http://www.crwflags.com/fotw/images/d/do.gif'),
 ('Ecuador', 0, 0, 1, 'South America', 'http://www.worldatlas.com/webimage/flags/countrys/zzzflags/eclarge.jpg'),
 ('El Salvador', 2, 2, 0, 'Central America', 'http://www.crwflags.com/fotw/images/s/sv.gif'),
 ('Estonia', 1, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/e/ee.gif'),
 ('Finland', 2, 2, 3, 'Europe', 'http://www.crwflags.com/fotw/images/f/fi.gif'),
 ('France', 0, 0, 7, 'Europe', 'http://www.crwflags.com/fotw/images/f/fr.gif'),
 ('Georgia, Asia', 2, 2, 0, 'Asia', 'http://www.crwflags.com/fotw/images/g/ge.gif'),
 ('Germany', 1, 0, 3, 'Europe', 'http://www.crwflags.com/fotw/images/d/de.gif'),
 ('Greece', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/g/gr.gif'),
 ('Honduras', 1, 0, 1, 'Central America', 'http://www.crwflags.com/fotw/images/h/hn.gif'),
 ('Hungary', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/h/hu.gif'),
 ('India', 0, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/in.gif'),
 ('Indonesia', 1, 1, 0, 'Asia', 'http://www.crwflags.com/fotw/images/i/id.gif'),
 ('Iraq', 1, 0, 1, 'Asia', 'http://www.crwflags.com/fotw/images/i/iq.gif'),
 ('Ireland', 2, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/i/ie.gif'),
 ('Italy', 1, 1, 3, 'Europe', 'http://www.crwflags.com/fotw/images/i/it.gif'),
 ('Kenya', 1, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/k/ke.gif'),
 ('Lesotho', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/l/ls.gif'),
 ('Lithuania', 1, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/l/lt.gif'),
 ('Macedonia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mk.gif'),
 ('Mali', 0, 1, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/m/ml.gif'),
 ('Malta', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/mt.gif'),
 ('Mexico', 3, 0, 6, 'Central America', 'http://www.crwflags.com/fotw/images/m/mx.gif'),
 ('Montenegro', 3, 2, 1, 'Europe', 'http://www.crwflags.com/fotw/images/m/me.gif'),
 ('Morocco', 2, 0, 3, 'Northern Africa', 'http://www.crwflags.com/fotw/images/m/ma.gif'),
 ('Mozambique', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/m/mz.gif'),
 ('Namibia', 0, 0, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/n/na.gif'),
 ('New Zealand', 0, 0, 1, 'Oceania', 'http://www.crwflags.com/fotw/images/n/nz.gif'),
 ('Nicaragua', 1, 1, 0, 'Central America', 'http://www.crwflags.com/fotw/images/n/ni.gif'),
 ('Norway', 0, 1, 0, 'Europe', 'http://www.crwflags.com/fotw/images/n/no.gif'),
 ('Pakistan', 1, 0, 2, 'Asia', 'http://www.crwflags.com/fotw/images/p/pk.gif'),
 ('Panama', 0, 0, 2, 'Central America', 'http://www.crwflags.com/fotw/images/p/pa.gif'),
 ('Paraguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/p/py.gif'),
 ('Peru', 2, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/p/pe.gif'),
 ('Poland', 4, 4, 3, 'Europe', 'http://www.crwflags.com/fotw/images/p/pl.gif'),
 ('Qatar', 0, 0, 1, 'Asia', 'http://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'),
 ('Romania', 4, 4, 0, 'Europe', 'http://www.crwflags.com/fotw/images/r/ro.gif'),
 ('Russia', 2, 1, 3, 'Europe, Asia', 'http://www.crwflags.com/fotw/images/r/ru.gif'),
 ('Serbia', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/r/rs.gif'),
 ('Slovakia', 2, 2, 0, 'Europe', 'http://www.crwflags.com/fotw/images/s/sk.gif'),
 ('Somalia', 1, 0, 0, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/s/so.gif'),
 ('South Africa', 3, 2, 4, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/za.gif'),
 ('Spain', 1, 2, 13, 'Europe', 'http://www.crwflags.com/fotw/images/e/es.gif'),
 ('Swaziland', 1, 1, 1, 'Southern Africa', 'http://www.crwflags.com/fotw/images/s/sz.gif'),
 ('Sweden', 2, 3, 1, 'Europe', 'http://www.crwflags.com/fotw/images/s/se.gif'),
 ('Tanzania', 0, 1, 2, 'Sub Saharan Africa', 'http://www.crwflags.com/fotw/images/t/tz.gif'),
 ('The Netherlands', 6, 3, 8, 'Europe', 'http://www.crwflags.com/fotw/images/n/nl.gif'),
 ('Turkey', 0, 0, 1, 'Europe', 'http://www.crwflags.com/fotw/images/t/tr.gif'),
 ('Ukraine', 1, 1, 1, 'Europe', 'http://www.crwflags.com/fotw/images/u/ua.gif'),
 ('United Kingdom', 6, 4, 7, 'Europe', 'http://www.crwflags.com/fotw/images/g/gb.gif'),
 ('United States', 8, 11, 6, 'North America', 'http://www.crwflags.com/fotw/images/u/us.gif'),
 ('Uruguay', 1, 1, 1, 'South America', 'http://www.crwflags.com/fotw/images/u/uy.gif'),
 ('Venezuela', 0, 1, 0, 'South America', 'http://www.crwflags.com/fotw/images/v/ve.gif'),
 ('Zambia', 1, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zm.gif'),
 ('Zimbabwe', 0, 0, 2, 'Southern Africa', 'http://www.crwflags.com/fotw/images/z/zw.gif')]